name: Deploy to EC2
on: 
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/BANK-ALFY
          git pull origin main
          docker stop program
          docker rm program
          docker build -t bank-alfy:latest .
          docker run -d -p 80:8080 --name program bank-alfy:latest